//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Last_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTable
    {
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public double Minimum_Bid_Amount { get; set; }
        public System.TimeSpan Auction_Time { get; set; }
        public string Category { get; set; }
    }
}
